
const constants = {
  REQUEST_CURRENCIES: 'REQUEST_CURRENCIES',
  RECEIVE_CURRENCIES: 'RECEIVE_CURRENCIES',
  GET_CURRENCIES: 'GET_CURRENCIES',
  INVALIDATE_BANKSLUG: 'INVALIDATE_BANKSLUG',
  SELECT_BANKSLUG: 'SELECT_BANKSLUG',
  SELECT_CURRENCY: 'SELECT_CURRENCY',
  GET_CURRENCY_BY_SHORTNAME: 'GET_CURRENCY_BY_SHORTNAME',
  UPDATE_CURRENCIES: 'UPDATE_CURRENCIES',
  DEFAULT_CURRENCY_SHORTNAME: 'ISK'
}

export default constants
